# Generated by Django 5.1 on 2024-09-03 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
