# Generated by Django 5.1 on 2024-09-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_training_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='category',
            field=models.CharField(choices=[('informasi_teknologi', 'Informasi Teknologi'), ('marketing', 'Marketing'), ('bisnis', 'Bisnis'), ('other', 'Other')], max_length=20),
        ),
    ]
